# Site settings
title: Sadhana Ramani
email: Sadhana.Ramani204@gmail.com
description: > # keep this and put description below
  Game Programmer
url: "https://SDRamani.github.io" # the base hostname & protocol for your site
linkedin_url: "https://www.linkedin.com/in/sadhana-ramani/"
github_username: SDRamani
footer_text: "This site uses <a href='https://github.com/gamingportfolio/urban-theme-portfolio'>urban-theme (portfolio)</a>."

# Build settings
markdown: kramdown
permalink: pretty
